# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20170812_2121'),
        ('myblog', '0003_auto_20170813_1444'),
    ]

    operations = [
    ]
